name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run tests
        run: gradle test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentages
        run: |
          echo "Code coverage: ${{ steps.jacoco.outputs.coverage }}"
          echo "Branch coverage: ${{ steps.jacoco.outputs.branches }}"

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-helloworld:latest

      - name: Check Code Coverage
        env:
          COVERAGE: ${{ steps.jacoco.outputs.coverage }}
          BRANCHES: ${{ steps.jacoco.outputs.branches }}
        run: |
          # This part needs to be customized based on your previous run's coverage
          # You'll need to store previous coverage in a file or use GitHub Actions cache
          echo "Current coverage: $COVERAGE"
          echo "Current branch coverage: $BRANCHES"
          # Add logic to compare with previous run