name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run tests
        run: gradle test jacocoTestReport

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Retrieve previous coverage
        uses: actions/cache@v3
        id: previous-coverage
        with:
          path: |
            previous-coverage.txt
            previous-branch-coverage.txt
          key: ${{ runner.os }}-coverage-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-coverage-

      - name: Check Code Coverage
        env:
          CURRENT_COVERAGE: ${{ steps.jacoco.outputs.coverage }}
          CURRENT_BRANCH_COVERAGE: ${{ steps.jacoco.outputs.branches }}
        run: |
          # Read previous coverage
          PREV_COVERAGE=$(cat previous-coverage.txt 2>/dev/null || echo "0")
          PREV_BRANCH_COVERAGE=$(cat previous-branch-coverage.txt 2>/dev/null || echo "0")
          
          
          CURRENT_COVERAGE_NUM=$(echo "$CURRENT_COVERAGE" | sed 's/%//')
          CURRENT_BRANCH_COVERAGE_NUM=$(echo "$CURRENT_BRANCH_COVERAGE" | sed 's/%//')
          
          PREV_COVERAGE_NUM=$(echo "$PREV_COVERAGE" | sed 's/%//')
          PREV_BRANCH_COVERAGE_NUM=$(echo "$PREV_BRANCH_COVERAGE" | sed 's/%//')
          
          
          if (( $(echo "$CURRENT_COVERAGE_NUM < $PREV_COVERAGE_NUM" | bc -l) )) || 
             (( $(echo "$CURRENT_BRANCH_COVERAGE_NUM < $PREV_BRANCH_COVERAGE_NUM" | bc -l) )); then
            echo "Coverage has decreased:"
            echo "Previous Coverage: $PREV_COVERAGE"
            echo "Current Coverage: $CURRENT_COVERAGE"
            echo "Previous Branch Coverage: $PREV_BRANCH_COVERAGE"
            echo "Current Branch Coverage: $CURRENT_BRANCH_COVERAGE"
            exit 1
          fi
          
          
          echo "$CURRENT_COVERAGE" > previous-coverage.txt
          echo "$CURRENT_BRANCH_COVERAGE" > previous-branch-coverage.txt

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-helloworld:latest